/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pravega.client.schema.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PressureData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5747158313911563012L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PressureData\",\"namespace\":\"io.pravega.client.schema.example.avro\",\"fields\":[{\"name\":\"pressure\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PressureData> ENCODER =
      new BinaryMessageEncoder<PressureData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PressureData> DECODER =
      new BinaryMessageDecoder<PressureData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PressureData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PressureData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PressureData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PressureData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PressureData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PressureData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PressureData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PressureData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private double pressure;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PressureData() {}

  /**
   * All-args constructor.
   * @param pressure The new value for pressure
   */
  public PressureData(java.lang.Double pressure) {
    this.pressure = pressure;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pressure;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pressure = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'pressure' field.
   * @return The value of the 'pressure' field.
   */
  public double getPressure() {
    return pressure;
  }


  /**
   * Sets the value of the 'pressure' field.
   * @param value the value to set.
   */
  public void setPressure(double value) {
    this.pressure = value;
  }

  /**
   * Creates a new PressureData RecordBuilder.
   * @return A new PressureData RecordBuilder
   */
  public static io.pravega.client.schema.example.avro.PressureData.Builder newBuilder() {
    return new io.pravega.client.schema.example.avro.PressureData.Builder();
  }

  /**
   * Creates a new PressureData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PressureData RecordBuilder
   */
  public static io.pravega.client.schema.example.avro.PressureData.Builder newBuilder(io.pravega.client.schema.example.avro.PressureData.Builder other) {
    if (other == null) {
      return new io.pravega.client.schema.example.avro.PressureData.Builder();
    } else {
      return new io.pravega.client.schema.example.avro.PressureData.Builder(other);
    }
  }

  /**
   * Creates a new PressureData RecordBuilder by copying an existing PressureData instance.
   * @param other The existing instance to copy.
   * @return A new PressureData RecordBuilder
   */
  public static io.pravega.client.schema.example.avro.PressureData.Builder newBuilder(io.pravega.client.schema.example.avro.PressureData other) {
    if (other == null) {
      return new io.pravega.client.schema.example.avro.PressureData.Builder();
    } else {
      return new io.pravega.client.schema.example.avro.PressureData.Builder(other);
    }
  }

  /**
   * RecordBuilder for PressureData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PressureData>
    implements org.apache.avro.data.RecordBuilder<PressureData> {

    private double pressure;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.pravega.client.schema.example.avro.PressureData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pressure)) {
        this.pressure = data().deepCopy(fields()[0].schema(), other.pressure);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing PressureData instance
     * @param other The existing instance to copy.
     */
    private Builder(io.pravega.client.schema.example.avro.PressureData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.pressure)) {
        this.pressure = data().deepCopy(fields()[0].schema(), other.pressure);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'pressure' field.
      * @return The value.
      */
    public double getPressure() {
      return pressure;
    }


    /**
      * Sets the value of the 'pressure' field.
      * @param value The value of 'pressure'.
      * @return This builder.
      */
    public io.pravega.client.schema.example.avro.PressureData.Builder setPressure(double value) {
      validate(fields()[0], value);
      this.pressure = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pressure' field has been set.
      * @return True if the 'pressure' field has been set, false otherwise.
      */
    public boolean hasPressure() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pressure' field.
      * @return This builder.
      */
    public io.pravega.client.schema.example.avro.PressureData.Builder clearPressure() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PressureData build() {
      try {
        PressureData record = new PressureData();
        record.pressure = fieldSetFlags()[0] ? this.pressure : (java.lang.Double) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PressureData>
    WRITER$ = (org.apache.avro.io.DatumWriter<PressureData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PressureData>
    READER$ = (org.apache.avro.io.DatumReader<PressureData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.pressure);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.pressure = in.readDouble();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.pressure = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










